ナビバーの実装
yanbaru-expert/team_project_61 pull request #41
Opened 2022-02-19 14:24 UTC by mczloves

close #11 

## 実装内容
- Bootstrap のナビバーを利用して，次の図のようなナビバーを作成
  - `app/views/layouts/_header.html.erb` を編集
  - `.fixed-top` を使用して上に固定すること
  - ロゴは `app/assets/images/yanbaru_expert_logo.png` を利用すること
  - リンクは `link_to` ヘルパーメソッドを使用すること
  - PHPテキスト教材のパスは `texts_path(genre: "php")`, 動画教材は `movies_path(genre: "php")` とすること
  - `md` サイズ未満で「ハンバーガーメニュー」に切り替わるようにすること
  - コンテンツがヘッダーに隠れないように調整
  - デベロッパーツールでヘッダーの高さを調べ， `body` タグに `padding-top` を設定

## 確認内容
- ログイン時・ログアウト時の表示が上記画像と同じような形式になっているかを確認
- ヘッダーが上に固定されていることを確認（ブラウザの縦幅を短めにしてスクロール）
- `768px` 未満で「ハンバーガーメニュー」に変化すること
- 「ドロップダウン」「ハンバーガーメニュー」が問題なく動作すること
- リンクが正常に機能していること

リンク                | URL
-------------------|---------------------------------------
ナビバーのロゴ            | http://localhost:3000
Ruby/Railsテキスト教材 | http://localhost:3000/texts
Ruby/Rails動画教材 | http://localhost:3000/movies
PHPテキスト教材        | http://localhost:3000/texts?genre=php
PHP動画教材        | http://localhost:3000/movies?genre=php

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

## 備考

2022-02-21 11:34 UTC, great084 reviewed
ナビバーの実装自体はOKです。
scssの記載内容について確認お願いします。

2022-02-21 11:34 UTC, great084 commented on app/assets/stylesheets/application.scss
> +}
.base-containerクラスはすでに、6行目で定義済みです。
同一名クラスの上書きは不具合のもとになるので、やめましょう

また、各画面の最大幅(max-width)は、application_helper.rbで設定しているためここでは設定不要です。

2022-02-22 16:59 UTC, great084 requested changes
以下のIssueで設定した画面設定を槊杖しようとしていますがなぜでしょうか？
https://github.com/yanbaru-expert/team_project_61/issues/3

2022-02-22 16:59 UTC, great084 commented on app/assets/stylesheets/application.scss
> -}
こちらの設定は削除しないでください。
画面サイズごとに最大幅を設定しています。

2022-02-22 16:59 UTC, great084 commented on app/assets/stylesheets/application.scss
> +  width: 80%;
container-fluid(width100%)のextendやwidth設定は不要です。
削除されている、mx-sm ~ mx-xlが画面幅毎の最大サイズを設定しています。

2022-02-23 01:00 UTC, mczloves commented on app/assets/stylesheets/application.scss
> -}
承知いたしました。

2022-02-23 08:42 UTC, great084 approved these changes
![エンジニアを褒めるネコ:LGTM](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/01_LGTM.png)

2022-02-24 13:20 UTC, merged