Rails動画教材ページの実装
yanbaru-expert/team_project_61 pull request #46
Opened 2022-03-08 16:37 UTC by kounodaichi

close #15 

## 実装内容
- Rails動画教材の一覧ページを作成
  - 表示するジャンルは `Movie::RAILS_GENRE_LIST` に制限
  - Bootstrapの `Cards` や `Grid System` を用いてスタイルを作成
  - `each` を使わず「[コレクションをレンダリング]
  - 各動画にレベル表示を入れる
  - カードの下側部分に `height` を指定して揃える
  - 動画教材ページでしか利用しないスタイルは `app/assets/stylesheets/movies.scss` を作成して書き込む
  - 広告は実装しない
  - ページネーションは別タスク
  - 「視聴済みボタン」はボタンの配置のみ
## 確認内容
- 画像のようにレスポンシブ対応ができているかどうかを確認
- カードの高さが一定になっているか確認
- PHPの動画教材が表示されていないことを確認

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

2022-03-11 15:44 UTC, great084 requested changes
Gridを実装する際に、row row-cols-1 row-cols-sm-2 row-cols-md-3を使用しかつ直下のタグでcardを設定しているためcard間のスペースが無くなってしまっています。
解決する方法としては、以下のいずれかです

このままrow row-cols-1 row-cols-sm-2 row-cols-md-3を使用するのであれば、直下にpadding のクラスを定義したタグ(ex <div class="p-2">)を追加し、そのもう一層下にcardを指定したタグを持ってくる
>・各cardのレイアウトは揃っているが、間隔がないこと

row row-cols-1 row-cols-sm-2 row-cols-md-3の代わりに、カラム内にpaddingがデフォルト設定されている、col-12 col-md-6 col-lg-4などのクラスを使用する。

（参考）https://getbootstrap.jp/docs/4.5/layout/grid/#grid-options

2022-03-11 15:44 UTC, great084 commented on app/assets/stylesheets/movies.scss
> +}
cardはbootstrapの定義済みクラスですのでオーバーライドするのはやめましょう。
また高さを固定するのは、card全体ではなく、カードの下側部分だけです。
>カードの下側部分に height を指定して揃える

2022-03-11 15:44 UTC, great084 commented on app/views/movies/_movie.html.erb
> +  <div class="card" style="width: 23rem;">
幅固定を入れてしまったら、レスポンシブでレイアウト崩れが発生します。

2022-03-11 15:44 UTC, great084 commented on app/views/movies/_movie.html.erb
> +     <iframe class="embed-responsive-item" src= <%= (movie.url) %> frameborder="0" style="border:0" allowfullscreen></iframe>
iframを直接記載するのではなく、
`app/helpers/movies_helper.rb` で定義した、`embed_youtube(url)`を呼び出しましょう。

2022-03-17 03:19 UTC, kounodaichi commented on app/assets/stylesheets/movies.scss
> +}
カード全体ではなく、カードの下側"card-title"を指定しました。
下側というのはカードの”タイトル部分”という理解でよろしかってでしょうか？

2022-03-17 03:19 UTC, kounodaichi commented on app/views/movies/_movie.html.erb
> +  <div class="card" style="width: 23rem;">
削除いたしました。

2022-03-17 03:26 UTC, kounodaichi commented on app/views/movies/_movie.html.erb
> +     <iframe class="embed-responsive-item" src= <%= (movie.url) %> frameborder="0" style="border:0" allowfullscreen></iframe>
`iframe`から`embed_youtube(url)`に変更しました。
確認宜しくお願いいたします。

2022-03-18 10:20 UTC, great084 reviewed
<img width="421" alt="image" src="https://user-images.githubusercontent.com/36526480/158985341-fa80b396-78ca-4d02-ab0d-a2bc50b1ff1a.png">
カードとカードが上下でくっついているので、余白を取りましょう。

2022-03-18 10:20 UTC, great084 commented on app/views/layouts/application.html.erb
> +=end%>
不要なコメントは削除しましょう。

2022-03-18 10:20 UTC, great084 commented on app/views/movies/_movie.html.erb
> +    <p class="card-title"><%= "Lv.#{movie_counter +1 } :" %><%= movie.title %></p>
bootstrapのcardを使う際には、以下を参考にしてcard-bodyを入れると、card内側にパディングが設定されます

https://getbootstrap.jp/docs/4.2/components/card/

ボタンはblock要素にして全幅表示にしてください。
あと、「読破済み」ではなく、「視聴済みです」

2022-03-21 13:31 UTC, great084 approved these changes
![エンジニアを褒めるネコ:LGTM](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/01_LGTM.png)

2022-03-23 13:35 UTC, merged