Railsテキスト教材一覧ページの実装
yanbaru-expert/team_project_61 pull request #47
Opened 2022-03-09 11:40 UTC by sakaiken18

close #13 

## 実装内容
- Railsテキスト教材一覧ページを作成
  - 表示するジャンルを`Text::RAILS_GENRE_LIST`に制限
  - Bootstrapの`cards`と`Grid System`を用いて実装
  - 検索機能・広告は未実装
  - 「読破済みボタン」は配置のみ(機能は未実装）

## 確認内容
- レスポンシブ対応ができているか確認
- ブラウザの横幅次第でカードの横幅が長くなりすぎていないか確認
- PHPのテキスト教材が表示されていないか確認

## 参考資料（必要があれば）
[【公式】Bootstrap Cards](https://getbootstrap.jp/docs/4.5/components/card/)
[【公式】Bootstrap Grid system](https://getbootstrap.jp/docs/4.5/layout/grid/)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2022-03-11 15:19 UTC, great084 requested changes
>見本通りにできていないところはカードとカードの間にスペースがなく、詰まった状態で表示されしまうところです。
>見本通りにするための改善方法もご教示していただけると助かります。よろしくお願いいたします。

Gridを実装する際に、`row row-cols-1 row-cols-sm-2 row-cols-md-3`を使用しかつ直下のタグでcardを設定しているためcard間のスペースが無くなってしまっています。
解決する方法としては、以下のいずれかです

- このまま`row row-cols-1 row-cols-sm-2 row-cols-md-3`を使用するのであれば、直下にpadding のクラスを定義したタグ(ex `<div class="p-2">`)を追加し、そのもう一層下にcardを指定したタグを持ってくる

- `row row-cols-1 row-cols-sm-2 row-cols-md-3`の代わりに、カラム内にpaddingがデフォルト設定されている、`col-12 col-md-6 col-lg-4`などのクラスを使用する。

（参考）https://getbootstrap.jp/docs/4.5/layout/grid/#grid-options



またスタイルの定義に関してもいくつか指摘をしているので、対応確認お願いします。

2022-03-11 15:19 UTC, great084 commented on app/assets/stylesheets/texts.scss
> +}
application.scssで定義されているclassですので、改めてここで定義する必要はありません。

2022-03-11 15:19 UTC, great084 commented on app/assets/stylesheets/texts.scss
> +}
bootstrapで用意されているclassをオーバーライドするのはやめましょう。
（他の箇所で当該classをbootstarpのデフォルト設定と思って使ったときに、思わぬ影響が出ます）
追加したいスタイルは独自クラスを追加してそこに定義しましょう。

2022-03-11 15:19 UTC, great084 commented on app/assets/stylesheets/texts.scss
> +}
btn-blockの誤記ではないでしょうか？
また、btn-blockであれば、bootstarpで定義されているためスタイル定義は不要です。

2022-03-11 15:19 UTC, great084 commented on app/views/texts/_text.html.erb
> +    【<%= text.genre %>】
ジャンルは日本語化されたものを出力してください。

2022-03-13 10:44 UTC, sakaiken18 commented on app/assets/stylesheets/texts.scss
> +}
削除しました。

2022-03-13 10:46 UTC, sakaiken18 commented on app/assets/stylesheets/texts.scss
> +}
.row　と　.card　は削除して
.content-card にスタイルを追加しました。
見本のdevtoolを参考にしましたが、合ってますでしょうか？

2022-03-13 10:47 UTC, sakaiken18 commented on app/assets/stylesheets/texts.scss
> +}
誤記でしたので削除しました。

2022-03-13 10:47 UTC, sakaiken18 commented on app/views/texts/_text.html.erb
> +    【<%= text.genre %>】
日本語化されたものが出力されるように修正しました。

2022-03-14 17:14 UTC, great084 commented on app/views/texts/_text.html.erb
> +<div class="row">
複数列表示ができないのは、繰り返し処理の中に `<div class="row">`を入れてしまっているためです。
繰り返し処理の外に定義すればうまくいくはずです。

2022-03-14 22:32 UTC, sakaiken18 commented on app/views/texts/_text.html.erb
> +<div class="row">
修正しました。
やっと見本に近い形で表示できました。
ご確認お願いいたします。

2022-03-16 12:56 UTC, great084 approved these changes
![寿司ゆき:ok](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/03.png)

2022-03-18 13:02 UTC, merged